### ISSUE TITLE
IntegrityError: null value in column "externalreference_stage" in dimManuscriptVersion.pushDeletes

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline-sql-prototype#113]
### 1. In _csv-generator_ (or using Docker):

```bash
pipenv run python -m csv_generator.process_xml_zip \
  --source-zip /path/to/ejp_eLife_2018_08_07_02_02_28_2018_08_08_02_02_28.zip \
  --output-dir ../output
```

### 2. In _db-manager_ (or using Docker):

```bash
pipenv run python -m db_manager import-data --source-dir ../output/
```

### 3. Run step 2 again.

This time it fails with:

```
INFO:db_manager.processing:staging: db_manager.dimManuscriptVersionHistory {'file_path': '../output/1533694105_stages.csv'}
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/__main__.py", line 88, in <module>
    main()
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/__main__.py", line 76, in main
    is_batch_mode=args.batch
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/processing.py", line 151, in process_source_dir
    process_filenames(connection, filenames, is_batch_mode=is_batch_mode)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/processing.py", line 144, in process_filenames
    connection, staging_instructions, is_batch_mode=is_batch_mode
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/processing.py", line 135, in process_staging_instructions_group
    staging_module.applyChanges(connection, source=None)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/dimManuscript.py", line 156, in applyChanges
    cascadeRetirements(conn, 'dimManuscript')
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/dimManuscript.py", line 81, in cascadeRetirements
    dimManuscriptVersion.cascadeRetirements(conn, 'dimManuscript')
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/dimManuscriptVersion.py", line 81, in cascadeRetirements
    pushDeletes(conn)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/dimManuscriptVersion.py", line 160, in pushDeletes
    """
psycopg2.IntegrityError: null value in column "externalreference_stage" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, 01-01-2018-RA-eLife-34741.xml, 0, 0, null, null, null, -1, D).
```

### 4. Run step 2 again.

Now it fails with:

```
INFO:db_manager.processing:staging: db_manager.dimManuscript {'file_path': '../output/1533694105_manuscripts.csv'}
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/__main__.py", line 88, in <module>
    main()
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/__main__.py", line 76, in main
    is_batch_mode=args.batch
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/processing.py", line 151, in process_source_dir
    process_filenames(connection, filenames, is_batch_mode=is_batch_mode)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/processing.py", line 144, in process_filenames
    connection, staging_instructions, is_batch_mode=is_batch_mode
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/processing.py", line 132, in process_staging_instructions_group
    staging_module.stage_csv(connection, **staging_parameters)
  File "/home/deuser/_git_/elife/data-pipeline/data-pipeline/db-manager/db_manager/dimManuscript.py", line 44, in stage_csv
    page_size=1000
  File "/home/deuser/.py-envs/db-manager-v_kc2Kgn/lib/python3.5/site-packages/psycopg2/extras.py", line 1277,in execute_values
    cur.execute(b''.join(parts))
psycopg2.IntegrityError: duplicate key value violates unique constraint "dimmanuscript_externalreference_manuscript_key"
DETAIL:  Key (externalreference_manuscript)=(01-01-2018-RA-eLife-34741.xml) already exists.
```

## Expected behaviour:

It should never fail when importing the same file again. The resulting dimension database should be no different whether it was imported once or twice.

## Potential cause

We may just need to remove `NOT NULL` from the staging table columns (but should add a test to prove it).

**Comment by de-code** [comment]
@lsh-0 is that something you would like to look at?

**Comment by lsh-0** [comment]
I can replicate this, investigating

**Comment by lsh-0** [comment]
PR: https://github.com/elifesciences/data-pipeline/pull/115/files
