### ISSUE TITLE
fresh installation, ./csv-data created and owned by root, fails with write denied

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/data-pipeline-sql-prototype#96]
Following the README and running:

`data-pipeline docker-compose run --rm csv-generator --source-zip '/example-data/xml-set-1' --output-dir '/csv-data'`

I get:

```
...
Successfully tagged data-pipeline/csv-generator:develop
WARNING: Image for service csv-generator was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

INFO:__main__:processing: /example-data/xml-set-1
  0%|                                                                                                                                              | 0/14 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/csv-generator/csv_generator/process_xml_zip.py", line 125, in <module>
    main()
  File "/usr/local/csv-generator/csv_generator/process_xml_zip.py", line 117, in main
    process_zip_or_extracted_dir(source_zip, output_dir, batch=args.batch)
  File "/usr/local/csv-generator/csv_generator/process_xml_zip.py", line 91, in process_zip_or_extracted_dir
    batch=batch
  File "/usr/local/csv-generator/csv_generator/process_xml_zip.py", line 64, in process_extracted_dir
    zip_file_name=source_zip.split(os.path.sep)[-1]
  File "/usr/local/csv-generator/csv_generator/consumers/__init__.py", line 43, in feed_consumers
    consumers = _init_consumers(create_date, output_dir, zip_file_name)
  File "/usr/local/csv-generator/csv_generator/consumers/__init__.py", line 61, in _init_consumers
    return [CONSUMERS[consumer](create_date, zip_file_name, output_dir) for consumer in CONSUMERS]
  File "/usr/local/csv-generator/csv_generator/consumers/__init__.py", line 61, in <listcomp>
    return [CONSUMERS[consumer](create_date, zip_file_name, output_dir) for consumer in CONSUMERS]
  File "/usr/local/csv-generator/csv_generator/consumers/consumer.py", line 17, in __init__
    self._write_row(self.headers)
  File "/usr/local/csv-generator/csv_generator/consumers/consumer.py", line 52, in _write_row
    with open(self.output_file, 'a', newline='') as output_file:
PermissionError: [Errno 13] Permission denied: '/csv-data/1514862245_manuscripts.csv'
```

The ./csv-data directory that gets created if it doesn't exist is owned by root and cannot be written to. This is a common problem with Docker apparently. Solution is to (on the host) remove that directory and re-create it, then run the command which yields:

```
INFO:__main__:processing: /example-data/xml-set-1
  0%|                                                                                                                                              | 0/14 [00:00<?, ?it/s]INFO:csv_generator.consumers.manuscript_consumer:no manuscript element found in with-empty-orcid-id-00009.xml
INFO:csv_generator.consumers.manuscript_consumer:manuscript id "" invalid, ignoring with-empty-orcid-id-00009.xml
INFO:csv_generator.consumers.manuscript_consumer:manuscript id "" invalid, ignoring with-empty-orcid-id-00009.xml
INFO:csv_generator.consumers.manuscript_consumer:no manuscript element found in with-person-roles-00015.xml
INFO:csv_generator.consumers.manuscript_consumer:manuscript id "" invalid, ignoring with-person-roles-00015.xml
INFO:csv_generator.consumers.manuscript_consumer:manuscript id "" invalid, ignoring with-person-roles-00015.xml
INFO:csv_generator.consumers.manuscript_consumer:no manuscript element found in with-person-addresses-00016.xml
INFO:csv_generator.consumers.manuscript_consumer:manuscript id "" invalid, ignoring with-person-addresses-00016.xml
INFO:csv_generator.consumers.manuscript_consumer:manuscript id "" invalid, ignoring with-person-addresses-00016.xml
INFO:__main__:complete  
```

**Comment by giorgiosironi** [comment]
No Salt formula is used here, but this is how we do it in a formula:
https://github.com/elifesciences/digests-formula/blob/master/salt/digests/init.sls#L7-L15

**Comment by lsh-0** [comment]
yes, I opened a ticket because I wasn't quite sure of the 'correct' way of fixing this. My impulse is to wrap those crazy docker commands in shell scripts and do any init'ing of dirs and things there.

**Comment by de-code** [comment]
The 'correct' way of using it is to use volumes rather than mounting the directory to the host. But that seemed awkward to work with in development.

Currently we are using a separate `csv-generator` user within the `csv-generator` Docker image. We could just run it as root, then it wouldn't have the permission issues. Otherwise the directory need to be created in a way that allows that user to write to it (e.g. `chmod a+w`). I tried that within the docker container but that is probably not working on the mounted directory itself. But we could write to a sub-directory instead.

(I've seen other fancy workarounds that are trying to map the user within the docker container to the host's user)

In general it seems to be better for containers to communicate via sockets / HTTP calls. But since we are dealing with potentially large files that may not be the best way.

**Comment by lsh-0** [comment]
all of docker is awkward to use in development. this would work:

`mkdir -p csv-data && data-pipeline docker-compose run --rm csv-generator --source-zip '/example-data/xml-set-1' --output-dir '/csv-data'`

**Comment by de-code** [comment]
`mkdir -p csv-data` alone will only work if the default permissions allow the `csv-generator` to write to it (for me that doesn't seem to be the case).

BTW just in case you weren't aware, you don't necessarily need to use docker in development. You can run the csv-generator without docker (see [csv-generator/README.md](https://github.com/elifesciences/data-pipeline/blob/develop/csv-generator/README.md)).
